### ISSUE TITLE
空格转换

### ISSUE THREAD

**Issue by Hzpiuini** [puppetdevz/picgo-plugin-rename-image#1]
您好作者，我最近在使用picgo和obsidian进行笔记管理。但我发现如果图片文件名中带有空格，在obsidian中是不能正常显示的。
我想是否能在上传的时候将图片重命名，将文件名中的空格转换为下划线"_"或者其他的字符呢？
叨扰了，十分感谢！

**Comment by puppetdevz** [comment]
> 您好作者，我最近在使用picgo和obsidian进行笔记管理。但我发现如果图片文件名中带有空格，在obsidian中是不能正常显示的。 我想是否能在上传的时候将图片重命名，将文件名中的空格转换为下划线"_"或者其他的字符呢？ 叨扰了，十分感谢！

目前是不支持的，这两天我改下，做下拓展后再发布一版

**Comment by puppetdevz** [comment]
> 您好作者，我最近在使用picgo和obsidian进行笔记管理。但我发现如果图片文件名中带有空格，在obsidian中是不能正常显示的。 我想是否能在上传的时候将图片重命名，将文件名中的空格转换为下划线"_"或者其他的字符呢？ 叨扰了，十分感谢！

@Hzpiuini 已更新解决。

![image](https://github.com/puppetdevz/picgo-plugin-rename-image/assets/46890209/bc91db4b-3006-4b55-98e8-a564e0dd6298)
